import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from './ui/view/molecule/toast/toaster';
import Provider from './provider';
import MSWComponent from './mocks/msw-component.mock';
import UserDeleteModal from './ui/user/user-info-navigator/user-delete-modal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
          rel="stylesheet"
        />
        <link href="https://webfontworld.github.io/vitro/VitroCore.css" rel="stylesheet" />
      </head>
      <body>
        <div className="bg-white">
          <Provider>
            <MSWComponent>{children}</MSWComponent>
          </Provider>
        </div>
        <Toaster />
        <UserDeleteModal />
      </body>
    </html>
  );
}
